### ISSUE TITLE
yaml-cpp dependency no longer available

### ISSUE THREAD

**Issue by scockram** [elnormous/rtmp_relay#5]
as stated in title, the yaml-capp here:

https://github.com/elnormous/yaml-cpp

no longer points to anything

**Comment by Genteure** [comment]
I think you can update the submodule to point to https://github.com/jbeder/yaml-cpp/commit/c045f7e8e76980e6b19337d2f14c4b8c1d1124ba instead of `https://github.com/elnormous/yaml-cpp/tree/c045f7e8e76980e6b19337d2f14c4b8c1d1124ba` (same commit)

**Comment by elnormous** [comment]
I fixed the url in https://github.com/elnormous/rtmp_relay/commit/cc376819316d2086bd39162dcc84910707938d68
